### ISSUE TITLE
Please add the SVG line element

### ISSUE THREAD

**Issue by Boscop** [kwohlfahrt/purescript-halogen-svg#3]
Please add the SVG line element:
https://www.w3schools.com/graphics/svg_line.asp

**Comment by kwohlfahrt** [comment]
Should be fixed in master (and tagged `v0.0.2`)

**Comment by Boscop** [comment]
Thanks!
Are there plans to add more elements, too? :)

**Comment by kwohlfahrt** [comment]
I have nothing against adding more elements - I'm using this for a personal project so I'll add them as people request (happy to take PRs) or I need them myself.
